version: '3.1'
services:
  rest-api:
    build: .
    ports:
      - 8081:8081
    depends_on:
      - liquibase
    restart: always
  liquibase:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: itacademy
      MYSQL_USER: root
      MYSQL_PASSWORD: Root
      MYSQL_ROOT_PASSWORD: Root